<?php

$query_array=array("headline"=>"List all Other Equipment",
                   "sql"=>"SELECT other_id, other_ip_address, other_network_name, other_type, other_description, other_linked_pc FROM other WHERE other_ip_address <> ' Not-Networked'",
                   "sort"=>"other_ip_address",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>"Go to System",
                                "var"=>array("other"=>"%other_id",
                                             "view"=>"other_system",
                                            ),
                               ),
                   "fields"=>array(
                                   "10"=>array("name"=>"other_ip_address",
                                               "head"=>"IP",
                                               "width"=>"160",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "20"=>array("name"=>"other_network_name",
                                               "head"=>"Attached Device",
                                               "width"=>"160",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"system.php",
                                                            "title"=>"Go to System",
                                                            "var"=>array("pc"=>"%other_linked_pc",
                                                                         "view"=>"summary",
                                                                        ),
                                                           ),
                                              ),
                                   "30"=>array("name"=>"other_type",
                                               "head"=>"Type",
                                               "align"=>"center",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "40"=>array("name"=>"other_description",
                                               "head"=>"Description",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                  ),
                  );
?>
