<?php

$query_array=array("headline"=>"List Systems with Startup-Software",
                   "sql"=>"SELECT * FROM startup, system WHERE startup_caption = '" . $_GET["name"] . "' AND startup_uuid  = system_uuid AND startup_timestamp = system_timestamp ",
                   "sort"=>"system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>"Go to System",
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>"UUID",
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"net_ip_address",
                                               "head"=>"IP",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>"Hostname",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "40"=>array("name"=>"system_os_name",
                                               "head"=>$l_osa,
                                               "show"=>$show_os,
                                              ),
                                   "50"=>array("name"=>"system_timestamp",
                                               "head"=>"Date Audited",
                                               "show"=>$show_date_audited,
                                               "align"=>"center",
                                              ),
                                   "60"=>array("name"=>"system_system_type",
                                               "head"=>"System Type",
                                               "show"=>$show_type,
                                               "align"=>"center",
                                              ),
                                   "70"=>array("name"=>"system_description",
                                               "head"=>"Description",
                                               "show"=>$show_description,
                                              ),
                                   "80"=>array("name"=>"net_domain",
                                               "head"=>"Domain",
                                               "show"=>$show_domain,
                                              ),
                                   "90"=>array("name"=>"system_service_pack",
                                               "head"=>"Servicepack",
                                               "show"=>$show_service_pack,
                                              ),
                                  ),
                  );
?>
