<?php

$query_array=array("headline"=>__("List Services for Host"),
                   "sql"=>"SELECT * FROM service, service_details WHERE sd_display_name = service_display_name AND service_uuid = '".$_REQUEST["pc"]."' AND service_timestamp = '".$GLOBALS["timestamp"]."' ",
                   "sort"=>"service_display_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>__("Systems installed this Service"),
                                "var"=>array("name"=>"%software_name",
                                             "version"=>"%software_version",
                                             "view"=>"all_services",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"service_display_name",
                                               "head"=>__("Name"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "help"=>"%service_path_name",
                                              ),
                                   "20"=>array("name"=>"service_start_mode",
                                               "head"=>__("Start Mode"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"service_state",
                                               "head"=>__("State"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "40"=>array("name"=>"service_started",
                                               "head"=>__("Started"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"",
                                               "head"=>__("Description"),
                                               "show"=>"y",
                                               "link"=>"n",
                                               "sort"=>"n",
                                               "search"=>"n",
                                               "help"=>"%sd_description",
                                              ),
                                  ),
                  );
?>
