<?php

$query_array=array("headline"=>"List Port-Exceptions for Host",
                   "sql"=>"SELECT * FROM firewall_ports where port_uuid = '".$_REQUEST["pc"]."' AND port_timestamp = '".$GLOBALS["timestamp"]."' ",
                   "sort"=>"port_profile, port_number",
                   "dir"=>"ASC",
                   "fields"=>array("10"=>array("name"=>"port_profile",
                                               "head"=>"Profile",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "20"=>array("name"=>"port_number",
                                               "head"=>"Port",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"port_protocol",
                                               "head"=>"Protocol",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "40"=>array("name"=>"port_scope",
                                               "head"=>"Scope",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
