<?php

$query_array=array("headline"=>"Uninstalled Software on Host",
                   "sql"=>"SELECT software_name, software_first_timestamp, software_timestamp, system_name FROM software, system WHERE software_name NOT LIKE '%Hotfix%' AND software_name NOT LIKE '%Update%' AND software_uuid = system_uuid AND software_uuid = '".$_REQUEST["pc"]."' AND software_timestamp <> system_timestamp ",
                   "sort"=>"software_first_timestamp",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>"Systems installed this Version of this Software",
                                "var"=>array("name"=>"%software_name",
                                             "version"=>"%software_version",
                                             "view"=>"systems_for_software_version",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"software_name",
                                               "head"=>"Software Name ",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"list.php",
                                                            "title"=>"Systems installed this Software",
                                                            "var"=>array("name"=>"%software_name",
                                                                         "view"=>"systems_for_software",
                                                                        ),
                                                           ),
                                              ),
                                   "20"=>array("name"=>"software_version",
                                               "head"=>"Version",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"software_first_timestamp",
                                               "head"=>"First Detected",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "40"=>array("name"=>"software_timestamp",
                                               "head"=>"Last Detected",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"Google",
                                               "head"=>"Google",
                                               "image"=>"images/button_google.gif",
                                               "align"=>"center",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "sort"=>"n",
                                               "search"=>"n",
                                               "get"=>array("file"=>"http://www.google.de/search",
                                                            "title"=>"External Link",
                                                            "var"=>array("q"=>"%system_name",
                                                                        ),
                                                            "target"=>"_BLANK",
                                                           ),
                                              ),
                                  ),
                  );
?>
