<?php

$query_array=array("headline"=>"List all Network Equipment",
                   "sql"=>"SELECT other_id, other_ip_address, other_network_name, other_type, other_description FROM other WHERE (other_ip_address <> '' AND other_ip_address <> ' Not-Networked') ",
                   "sort"=>"other_network_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>"Go to System",
                                "var"=>array("other"=>"%other_id",
                                             "view"=>"other_system",
                                            ),
                               ),
                   "fields"=>array(
                                   "10"=>array("name"=>"other_description",
                                               "head"=>"Description",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "20"=>array("name"=>"other_type",
                                               "head"=>"Type",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"other_ip_address",
                                               "head"=>"IP Address",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "40"=>array("name"=>"other_network_name",
                                               "head"=>"Network Name",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
