<?php

$query_array=array("headline"=>"List All Printers",
                   "sql"=>"SELECT other_id, other_linked_pc, other_network_name, other_description, other_p_port_name, other_location FROM other WHERE other_type = 'printer' ",
                   "sort"=>"other_network_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>"Go to Printer",
                                "var"=>array("other"=>"%other_id",
                                             "view"=>"other_system",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"other_linked_pc",
                                               "head"=>"UUID",
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"other_network_name",
                                               "head"=>"Name",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"system.php",
                                                            "title"=>"Go to System",
                                                            "var"=>array("pc"=>"%other_linked_pc",
                                                                         "view"=>"summary",
                                                                        ),
                                                           ),
                                              ),
                                   "30"=>array("name"=>"other_description",
                                               "head"=>"Description",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "40"=>array("name"=>"other_p_port_name",
                                               "head"=>"Port",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
