<?php

$query_array=array("headline"=>"List Keys for Software",
                   "sql"=>"SELECT ms_keys_name, ms_keys_cd_key, system_name, net_ip_address, system_uuid FROM ms_keys, system WHERE ms_keys_key_type LIKE '".urldecode($_GET["type"])."%' AND ms_keys_name LIKE '".urldecode($_GET["name"])."%' AND ms_keys_uuid = system_uuid AND ms_keys_timestamp = system_timestamp ",
                   "sort"=>"system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>"Go to System",
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>"UUID",
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"net_ip_address",
                                               "head"=>"IP",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>"Hostname",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "40"=>array("name"=>"ms_keys_name",
                                               "head"=>"Software",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"ms_keys_cd_key",
                                               "head"=>"Key",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
