<?php

$query_array=array("headline"=>"List all Hotfixes & Patches",
                   "sql"=>"SELECT count(software_name) AS software_count, software_name, software_version, software_publisher, software_url FROM software, system where (software_name LIKE '%hotfix%' OR software_name LIKE '%update%' OR software_name LIKE '%Service Pack%') AND software_uuid = system_uuid AND software_timestamp = system_timestamp GROUP BY software_name, software_version ",
                   "sort"=>"software_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>"Computers installed this Software",
                                "var"=>array("view"=>"systems_for_software",
                                             "name"=>"%software_name",
                                             "headline_addition"=>"%software_name",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"software_count",
                                               "head"=>"Count",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "sort"=>"n",
                                               "search"=>"n",
                                              ),
                                   "20"=>array("name"=>"software_name",
                                               "head"=>"Software Name",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"software_version",
                                               "head"=>"Version",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"list.php",
                                                            "title"=>"Computers installed this Version of this Software",
                                                            "var"=>array("view"=>"systems_for_software_version",
                                                                         "name"=>"%software_name",
                                                                         "version"=>"%software_version",
                                                                         "headline_addition"=>"%software_name",
                                                                        ),
                                                           ),
                                              ),

                                   "40"=>array("name"=>"software_publisher",
                                               "head"=>"Publisher",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"%software_url",
                                                            "title"=>"External Link",
                                                           ),
                                              ),
                                  ),
                  );
?>
