<?php

$query_array=array("headline"=>"List IE BHO's for Host",
                   "sql"=>"SELECT * FROM browser_helper_objects, system WHERE system_uuid = '".urldecode($_GET["pc"])."' AND bho_uuid = system_uuid AND bho_timestamp = system_timestamp",
                   "sort"=>"bho_program_file",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>"Systems installed this Software",
                                "var"=>array("view"=>"systems_for_bho",
                                             "name"=>"%bho_program_file",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"bho_program_file",
                                               "head"=>"Name",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "20"=>array("name"=>"bho_status",
                                               "head"=>"Status",
                                               "show"=>"y",
                                               "sort"=>"n",
                                               "help"=>"%bho_code_base",
                                              ),

                                   "30"=>array("name"=>"Google",
                                               "head"=>"Google",
                                               "image"=>"images/button_google.gif",
                                               "align"=>"center",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "sort"=>"n",
                                               "search"=>"n",
                                               "get"=>array("file"=>"http://www.google.de/search",
                                                            "title"=>"External Link",
                                                            "var"=>array("q"=>"%bho_program_file",
                                                                        ),
                                                            "target"=>"_BLANK",
                                                           ),
                                              ),
                                  ),
                  );
?>
