<?php

$query_array=array("headline"=>"List Startup-Software on Host",
                   "sql"=>"SELECT * FROM startup WHERE startup_uuid = '".$_REQUEST["pc"]."' AND startup_timestamp = '".$GLOBALS["timestamp"]."' ",
                   "sort"=>"startup_caption",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>"Hosts with this Startup-Software",
                                "var"=>array("view"=>"systems_for_startupsoftware",
                                             "name"=>"%startup_caption",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"startup_caption",
                                               "head"=>"Name",
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "20"=>array("name"=>"startup_user",
                                               "head"=>"User",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"startup_location",
                                               "head"=>"Location",
                                               "show"=>"y",
                                               "link"=>"n",
                                               "help"=>"%startup_command",
                                              ),

                                   "40"=>array("name"=>"startup_command",
                                               "head"=>"Executable",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "search"=>"n",
                                               "sort"=>"n",
                                               "image"=>"images/software.png",
                                               "help"=>"%startup_command",
                                              ),
                                  ),
                  );
?>
