<?php
$query_array=array("name"=>__("Domain Overview"),
                   "views"=>array("10"=>array(
                                                    "headline"=>__("Other Items Discovered in the last")." $other_detected ".__("Days"),
                                                    "sql"=>"SELECT * FROM other WHERE (other_mac_address <> '' AND other_first_timestamp > '" . adjustdate(0,0,-$other_detected) . "') ",
                                                    "sort"=>"other_ip_address",
                                                    "show"=>$show_other_discovered,
                                                    "get"=>array("file"=>"system.php",
                                                                 "title"=>__("Go to System"),
                                                                 "var"=>array("other"=>"%other_id",
                                                                              "view"=>"summary",
                                                                             ),
                                                                 ),
                                                    "fields"=>array("10"=>array("name"=>"other_ip_address",),
                                                                    "20"=>array("name"=>"other_network_name",
                                                                                "link"=>"y",
                                                                                ),
                                                                    "30"=>array("name"=>"other_type",),
                                                                    "40"=>array("name"=>"other_description",),
                                                                   ),
                                                    ),
                                  "20"=>array(
                                                    "headline"=>__("Systems Discovered in the last")." $system_detected ".__("Days"),
                                                    "sql"=>"SELECT system_name, net_ip_address, system_uuid, system_first_timestamp FROM system WHERE system_first_timestamp > '" . adjustdate(0,0,-$system_detected) . "000000'  ",
                                                    "sort"=>"system_name",
                                                    "show"=>$show_other_discovered,
                                                    "get"=>array("file"=>"system.php",
                                                                 "title"=>__("Go to System"),
                                                                 "var"=>array("pc"=>"%system_uuid",
                                                                              "view"=>"summary",
                                                                             ),
                                                                 ),
                                                    "fields"=>array("10"=>array("name"=>"net_ip_address",
                                                                                "link"=>"y",
                                                                                ),
                                                                    "20"=>array("name"=>"system_name",
                                                                                "link"=>"y",
                                                                                ),
                                                                    "30"=>array("name"=>"system_first_timestamp",),
                                                                   ),
                                                    ),
                                  "30"=>array(
                                                    "headline"=>__("Systems Not Audited in the last")." $days_systems_not_audited ".__("Days"),
                                                    "sql"=>"SELECT system_name, net_ip_address, system_uuid, system_first_timestamp FROM system WHERE system_timestamp < '" . adjustdate(0,0,-$days_systems_not_audited) . "000000' ",
                                                    "sort"=>"system_name",
                                                    "show"=>$show_other_discovered,
                                                    "get"=>array("file"=>"system.php",
                                                                 "title"=>__("Go to System"),
                                                                 "var"=>array("pc"=>"%system_uuid",
                                                                              "view"=>"summary",
                                                                             ),
                                                                 ),
                                                    "fields"=>array("10"=>array("name"=>"net_ip_address",
                                                                                "link"=>"y",
                                                                                ),
                                                                    "20"=>array("name"=>"system_name",
                                                                                "link"=>"y",
                                                                                ),
                                                                    "30"=>array("name"=>"system_first_timestamp",),
                                                                   ),                       
                                                    ),
                                ),
                  );

?>
