<?php

$query_array=array("name"=>"Hardware",
                   "image"=>"images/os_l.png",
                   "views"=>array("hard_drive"=>array(
                                                    "headline"=>"Fixed Disks",
                                                    "sql"=>"SELECT * FROM hard_drive, system WHERE hard_drive_uuid=system_uuid AND hard_drive_uuid = '" . $_GET["pc"] . "' AND hard_drive_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY hard_drive_index",
                                                    "image"=>"images/harddisk_l.png",
                                                    "fields"=>array("10"=>array("name"=>"hard_drive_index",),
                                                                    "20"=>array("name"=>"hard_drive_manufacturer",),
                                                                    "30"=>array("name"=>"hard_drive_interface_type",),
                                                                    "40"=>array("name"=>"hard_drive_model",),
                                                                    "50"=>array("name"=>"hard_drive_partitions",),
                                                                    "60"=>array("name"=>"hard_drive_size",),
                                                                    "70"=>array("name"=>"hard_drive_scsi_bus",),
                                                                    "80"=>array("name"=>"hard_drive_scsi_logical_unit",),
                                                                    "90"=>array("name"=>"hard_drive_scsi_port",),
                                                                   ),
                                                    ),
                                   "partition"=>array(
                                                    "headline"=>"Partitions",
                                                    "sql"=>"SELECT * FROM partition WHERE (partition_uuid = '" . $_GET["pc"] . "' && partition_timestamp = '".$GLOBAL["system_timestamp"]."') ",
                                                    "image"=>"images/partition_l.png",
                                                    "fields"=>array("10"=>array("name"=>"partition_device_id",),
                                                                    "20"=>array("name"=>"partition_caption",),
                                                                    "30"=>array("name"=>"partition_volume_name",),
                                                                    "40"=>array("name"=>"partition_boot_partition",),
                                                                    "50"=>array("name"=>"partition_bootable",),
                                                                    "60"=>array("name"=>"partition_size",),
                                                                    "70"=>array("name"=>"partition_file_system",),
                                                                    "80"=>array("name"=>"partition_free_space",),
                                                                   ),
                                                    ),
                                   "scsi_controller"=>array(
                                                    "headline"=>"SCSI Controller",
                                                    "sql"=>"SELECT * FROM scsi_controller, system  WHERE scsi_controller_uuid=system_uuid AND scsi_controller_uuid = '" . $_GET["pc"] . "' AND scsi_controller_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY scsi_controller_device_id",
                                                    "image"=>"images/scsi_l.png",
                                                    "fields"=>array("10"=>array("name"=>"scsi_controller_caption",),
                                                                    "20"=>array("name"=>"scsi_controller_manufacturer",),
                                                                   ),
                                                    ),
                                   "optical_drive"=>array(
                                                    "headline"=>"Optical Drive",
                                                    "sql"=>"SELECT * FROM optical_drive WHERE optical_drive_uuid = '" . $_GET["pc"] . "' AND optical_drive_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY optical_drive_drive",
                                                    "image"=>"images/optical_l.png",
                                                    "fields"=>array("10"=>array("name"=>"optical_drive_drive",),
                                                                    "20"=>array("name"=>"optical_drive_caption",),
                                                                   ),
                                                    ),
                                   "floppy"=>array(
                                                    "headline"=>"Floppy Drive",
                                                    "sql"=>"SELECT * FROM floppy WHERE floppy_uuid = '" . $_GET["pc"] . "' AND floppy_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/floppy_l.png",
                                                    "fields"=>array("10"=>array("name"=>"floppy_caption",),
                                                                    "20"=>array("name"=>"floppy_description",),
                                                                    "30"=>array("name"=>"floppy_manufacturer",),
                                                                   ),
                                                    ),
                                   "tape_drive"=>array(
                                                    "headline"=>"Tape Drive",
                                                    "sql"=>"SELECT * FROM tape_drive WHERE tape_drive_uuid = '" . $_GET["pc"] . "' AND tape_drive_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY tape_drive_id",
                                                    "image"=>"images/tape_l.png",
                                                    "fields"=>array("10"=>array("name"=>"tape_drive_manufacturer",),
                                                                    "20"=>array("name"=>"tape_drive_caption",),
                                                                    "30"=>array("name"=>"tape_drive_description",),
                                                                   ),
                                                    ),
                                   "processor"=>array(
                                                    "headline"=>"Processor",
                                                    "sql"=>"SELECT * FROM processor WHERE processor_uuid = '" . $_GET["pc"] . "' AND processor_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY processor_id",
                                                    "image"=>"images/processor_l.png",
                                                    "fields"=>array("10"=>array("name"=>"processor_socket_designation",),
                                                                    "20"=>array("name"=>"processor_manufacturer",),
                                                                    "30"=>array("name"=>"processor_caption",),
                                                                    "40"=>array("name"=>"processor_name",),
                                                                    "50"=>array("name"=>"processor_max_clock_speed",),
                                                                    "60"=>array("name"=>"processor_current_clock_speed",),
                                                                    "70"=>array("name"=>"processor_ext_clock",),
                                                                    "80"=>array("name"=>"processor_current_voltage",),
                                                                   ),
                                                    ),
                                   "bios"=>array(
                                                    "headline"=>"Bios",
                                                    "sql"=>"SELECT * FROM bios WHERE bios_uuid = '" . $_GET["pc"] . "' AND bios_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/bios_l.png",
                                                    "fields"=>array("10"=>array("name"=>"bios_description",),
                                                                    "20"=>array("name"=>"bios_manufacturer",),
                                                                    "30"=>array("name"=>"bios_serial_number",),
                                                                    "40"=>array("name"=>"bios_version",),
                                                                    "50"=>array("name"=>"bios_sm_bios_version",),
                                                                    "60"=>array("name"=>"bios_asset_tag",),
                                                                   ),
                                                    ),
                                   "memory"=>array(
                                                    "headline"=>"Memory",
                                                    "sql"=>"SELECT * FROM memory WHERE memory_uuid = '" . $_GET["pc"] . "' AND memory_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY memory_id",
                                                    "image"=>"images/memory_l.png",
                                                    "fields"=>array("10"=>array("name"=>"memory_bank",),
                                                                    "20"=>array("name"=>"memory_form_factor",),
                                                                    "30"=>array("name"=>"memory_type",),
                                                                    "40"=>array("name"=>"memory_detail",),
                                                                    "50"=>array("name"=>"memory_speed",),
                                                                    "60"=>array("name"=>"memory_capacity",),
                                                                   ),
                                                    ),
                                   "network_card"=>array(
                                                    "headline"=>"Network Card",
                                                    "sql"=>"SELECT * FROM network_card WHERE net_uuid = '" . $_GET["pc"] . "' AND net_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/network_device_l.png",
                                                    "fields"=>array("10"=>array("name"=>"net_adapter_type",),
                                                                    "20"=>array("name"=>"net_description",),
                                                                    "30"=>array("name"=>"net_manufacturer",),
                                                                    "40"=>array("name"=>"net_mac_address",),
                                                                    "50"=>array("name"=>"net_ip_address",),
                                                                    "60"=>array("name"=>"net_ip_subnet",),
                                                                    "70"=>array("name"=>"net_dns_server",),
                                                                    "80"=>array("name"=>"net_dns_server",),
                                                                    "90"=>array("name"=>"net_dns_server_2",),
                                                                    "100"=>array("name"=>"net_wins_primary",),
                                                                    "110"=>array("name"=>"net_wins_secondary",),
                                                                    "120"=>array("name"=>"net_dhcp_enabled",),
                                                                    "130"=>array("name"=>"net_dhcp_server",),
                                                                   ),
                                                    ),
                                   "video"=>array(
                                                    "headline"=>"Video Adapter",
                                                    "sql"=>"SELECT * FROM video WHERE video_uuid = '" . $_GET["pc"] . "' AND video_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/video_l.png",
                                                    "fields"=>array("10"=>array("name"=>"video_caption",),
                                                                    "20"=>array("name"=>"video_adapter_ram",),
                                                                    "30"=>array("name"=>"video_current_horizontal_res",),
                                                                    "40"=>array("name"=>"video_current_vertical_res",),
                                                                    "50"=>array("name"=>"video_current_refresh_rate",),
                                                                    "60"=>array("name"=>"video_current_number_colours",),
                                                                    "70"=>array("name"=>"video_driver_version",),
                                                                    "80"=>array("name"=>"video_driver_date",),
                                                                   ),
                                                    ),
                                   "monitor"=>array(
                                                    "headline"=>"Monitor",
                                                    "sql"=>"SELECT * FROM monitor WHERE monitor_uuid = '" . $_GET["pc"] . "' AND monitor_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/display_l.png",
                                                    "fields"=>array("10"=>array("name"=>"monitor_manufacturer",),
                                                                    "20"=>array("name"=>"monitor_model",),
                                                                    "30"=>array("name"=>"monitor_serial",),
                                                                    "40"=>array("name"=>"monitor_manufacture_date",),
                                                                   ),
                                                    ),
                                   "sound"=>array(
                                                    "headline"=>"Soundcard",
                                                    "sql"=>"SELECT * FROM sound WHERE sound_uuid = '" . $_GET["pc"] . "' AND sound_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/audio_l.png",
                                                    "fields"=>array("10"=>array("name"=>"sound_name",),
                                                                    "20"=>array("name"=>"sound_manufacturer",),
                                                                   ),
                                                    ),
                                   "keyboard"=>array(
                                                    "headline"=>"Keyboard",
                                                    "sql"=>"SELECT * FROM keyboard WHERE keyboard_uuid = '" . $_GET["pc"] . "' AND keyboard_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/keyboard_l.png",
                                                    "fields"=>array("10"=>array("name"=>"keyboard_caption",),
                                                                    "20"=>array("name"=>"keyboard_description",),
                                                                   ),
                                                    ),
                                   "keyboard"=>array(
                                                    "headline"=>"Keyboard",
                                                    "sql"=>"SELECT * FROM mouse WHERE mouse_uuid = '" . $_GET["pc"] . "' AND mouse_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/keyboard_l.png",
                                                    "fields"=>array("10"=>array("name"=>"mouse_description",),
                                                                    "20"=>array("name"=>"mouse_number_of_buttons",),
                                                                    "30"=>array("name"=>"mouse_port",),
                                                                   ),
                                                    ),
                                   "modem"=>array(
                                                    "headline"=>"Modem",
                                                    "sql"=>"SELECT * FROM modem WHERE modem_uuid = '" . $_GET["pc"] . "' AND modem_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY modem_attached_to",
                                                    "image"=>"images/modem_l.png",
                                                    "fields"=>array("10"=>array("name"=>"modem_device_type",),
                                                                    "20"=>array("name"=>"modem_description",),
                                                                    "30"=>array("name"=>"modem_attached_to",),
                                                                    "40"=>array("name"=>"modem_country_selected",),
                                                                   ),
                                                    ),
                                   "battery"=>array(
                                                    "headline"=>"Battery",
                                                    "sql"=>"SELECT * FROM battery WHERE battery_uuid = '" . $_GET["pc"] . "' AND battery_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/battery_l.png",
                                                    "fields"=>array("10"=>array("name"=>"battery_description",),
                                                                    "20"=>array("name"=>"battery_device_id",),
                                                                   ),
                                                    ),
                                   "printer"=>array(
                                                    "headline"=>"Printer",
                                                    "sql"=>"SELECT * FROM other WHERE other_type = 'printer' AND other_linked_pc = '" . $_GET["pc"] . "' AND other_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "image"=>"images/printer_l.png",
                                                    "fields"=>array("10"=>array("name"=>"other_description",),
                                                                    "20"=>array("name"=>"other_p_port_name",),
                                                                   ),
                                                    ),
                                   "usb"=>array(
                                                    "headline"=>"USB",
                                                    "sql"=>"SELECT * FROM usb WHERE usb_uuid = '" . $_GET["pc"] . "' AND usb_timestamp = '".$GLOBAL["system_timestamp"]."' AND usb_manufacturer <> '(Standard system devices)' AND usb_caption <> 'HID-compliant consumer control device' AND usb_manufacturer <> '(Standard USB Host Controller)' ORDER BY usb_caption",
                                                    "image"=>"images/usb_l.png",
                                                    "fields"=>array("10"=>array("name"=>"usb_caption",),
                                                                    "20"=>array("name"=>"usb_description",),
                                                                    "30"=>array("name"=>"usb_manufacturer",),
                                                                   ),
                                                    ),
                                ),
                  );
/*
" . $_GET["pc"] . "
".$GLOBAL["system_timestamp"]."
*/
?>
