<?php

$query_array=array("views"=>array("summary"=>array(
                                                    "headline"=>"Summary",
                                                    "sql"=>"SELECT * FROM network_card, system WHERE (system_uuid=net_uuid AND system_timestamp=net_timestamp) AND system_uuid = '" . $_GET["pc"] . "' AND  system_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/os_l.png",
                                                    "fields"=>array("10"=>array("name"=>"net_uuid",
                                                                                "show"=>"n",
                                                                               ),
                                                                    "20"=>array("name"=>"system_name",),
                                                                    "30"=>array("name"=>"system_description",),
                                                                    "40"=>array("name"=>"net_domain_role",),
                                                                    "50"=>array("name"=>"system_registered_user",),
                                                                    "60"=>array("name"=>"net_user_name",),
                                                                    "70"=>array("name"=>"net_domain",),
                                                                    "80"=>array("name"=>"system_system_type",),
                                                                    "90"=>array("name"=>"system_model",),
                                                                    "100"=>array("name"=>"system_id_number",),
                                                                    "110"=>array("name"=>"system_vendor",),
                                                                    "120"=>array("name"=>"system_os_name",),
                                                                    "130"=>array("name"=>"system_build_number",),
                                                                    "140"=>array("name"=>"system_uuid",),
                                                                    "150"=>array("name"=>"date_system_install",),
                                                                    "160"=>array("name"=>"net_ip_address",),
                                                                    "170"=>array("name"=>"net_ip_subnet",),
                                                                    "180"=>array("name"=>"net_dhcp_server",),
                                                                    "190"=>array("name"=>"system_first_timestamp",),
                                                                    "200"=>array("name"=>"system_timestamp",),
                                                                    "210"=>array("name"=>"system_memory",),
                                                                   ),
                                                ),
                                   "management"=>array(
                                                    "headline"=>"Remote Management",
                                                    "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $_GET["pc"] . "' AND  system_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"./images/display_l.png",
                                                    "fields"=>array("10"=>array("name"=>"RDP",
                                                                                "get"=>array("name"=>"Klick to Start RPD-Session",
                                                                                             "file"=>"launch_rdp.php",
                                                                                             "title"=>"Klick me!",
                                                                                             "var"=>array("launch"=>"%system_name",
                                                                                                         ),
                                                                                            ),
                                                                                ),
                                                                    "20"=>array("name"=>"VNC",
                                                                                "get"=>array("name"=>"Klick to Start VNC-Session",
                                                                                             "file"=>"launch_vnc.php",
                                                                                             "title"=>"Klick me!",
                                                                                             "var"=>array("launch"=>"%system_name",
                                                                                                         ),
                                                                                            ),
                                                                                ),
                                                                   ),
                                                    ),

                                 ),
                  );
?>
