<?php

$query_array=array("name"=>"Other System",
                   "image"=>"images/os_l.png",
                   "views"=>array("summary"=>array(
                                                    "headline"=>"Summary",
                                                    "sql"=>"SELECT * FROM other WHERE other_id = '".$_GET['other']."'",
                                                    "image"=>"./images/summary_l.png",
                                                    "fields"=>array("10"=>array("name"=>"other_network_name",),
                                                                    "20"=>array("name"=>"other_type",),
                                                                    "30"=>array("name"=>"system_registered_user",),
                                                                    "40"=>array("name"=>"other_ip_address",),
                                                                    "50"=>array("name"=>"other_mac_address",),
                                                                    "60"=>array("name"=>"other_timestamp",),
                                                                    "70"=>array("name"=>"other_manufacturer",),
                                                                    "80"=>array("name"=>"other_model",),
                                                                    "90"=>array("name"=>"other_serial",),
                                                                    "100"=>array("name"=>"other_location",),
                                                                    "120"=>array("name"=>"other_date_purchased",),
                                                                    "130"=>array("name"=>"other_value",),
                                                                    "140"=>array("name"=>"other_description",),
                                                                    "150"=>array("name"=>"",),
                                                                    "160"=>array("name"=>"Port Scan",
                                                                                "get"=>array("name"=>"Click me!",
                                                                                             "file"=>"list.php",
                                                                                             "title"=>"Click me!",
                                                                                             "var"=>array("pc"=>"%other_id",
                                                                                                          "view"=>"nmap_for_system",
                                                                                                         ),
                                                                                            ),
                                                                                ),
                                                                   ),
                                                    ),
                                ),
                  );
?>
