<?php
    $query_array=array("name"=>array("name"=>__("Security"),
                                     "sql"=>"SELECT `system_name` FROM `system` WHERE `system_uuid` = '" . $_GET["pc"] . "'",
                                    ),
                       "views"=>array("win_firewall"=>array(
                                                        "headline"=>__("Windows Firewall"),
                                                        "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $_GET["pc"] . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                        "image"=>"./images/firewall_l.png",
                                                        "fields"=>array("10"=>array("name"=>"firewall_enabled_domain", "head"=>__("Domain - Firewall Enabled"),),
                                                                        "20"=>array("name"=>"firewall_disablenotifications_domain", "head"=>__("Domain - Notifications to User"),),
                                                                        "30"=>array("name"=>"firewall_donotallowexceptions_domain", "head"=>__("Domain - Exceptions Allowed"),),
                                                                        "40"=>array("name"=>"firewall_enabled_standard", "head"=>__("Standard - Firewall Enabled"),),
                                                                        "50"=>array("name"=>"firewall_disablenotifications_standard", "head"=>__("Standard - Notifications to User"),),
                                                                        "60"=>array("name"=>"firewall_donotallowexceptions_standard", "head"=>__("Standard - Exceptions Allowed"),),
                                                                        "70"=>array("name"=>"", "head"=>__(""),),
                                                                        "80"=>array("head"=>__("Port Exceptions"),
                                                                                    "get"=>array("head"=>__("Click me!"),
                                                                                                 "file"=>"list.php",
                                                                                                 "title"=>__("Click me!"),
                                                                                                 "var"=>array("pc"=>"%system_uuid",
                                                                                                              "view"=>"port_exceptions_for_system",
                                                                                                              "headline_addition"=>"%system_name",
                                                                                                             ),
                                                                                                ),
                                                                                    ),
                                                                        "90"=>array("head"=>__("Program Exceptions"),
                                                                                    "get"=>array("head"=>__("Click me!"),
                                                                                                 "file"=>"list.php",
                                                                                                 "title"=>__("Click me!"),
                                                                                                 "var"=>array("pc"=>"%system_uuid",
                                                                                                              "view"=>"program_exceptions_for_system",
                                                                                                              "headline_addition"=>"%system_name",
                                                                                                             ),
                                                                                                ),
                                                                                    ),
                                                                       ),
                                                        ),
                                       "firewall_other"=>array(
                                                        "headline"=>__("Other Firewalls"),
                                                        "sql"=>"SELECT * from software WHERE software_uuid = '" . $_GET["pc"] . "' AND software_timestamp = '".$GLOBAL["system_timestamp"]."'
                                                                                             AND (software_name LIKE '%ZoneAlarm%'
                                                                                                  OR software_name LIKE '%Internet Security%'
                                                                                                  OR software_name LIKE '%Firewall%')",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/firewall_l.png",
                                                        "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                       ),
                                                        ),
                                       "antivirus_xp"=>array(
                                                        "headline"=>__("Windows Security Center Registered Antivirus"),
                                                        "sql"=>"SELECT * from system WHERE system_uuid = '" . $_GET["pc"] . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."'  AND (virus_name <> '' OR virus_manufacturer <> '') ",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/antivirus_l.png",
                                                        "fields"=>array("10"=>array("name"=>"virus_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"virus_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"virus_manufacturer", "head"=>__("Manufacturer"),),
                                                                        "40"=>array("name"=>"virus_uptodate", "head"=>__("Up-to-date"),),
                                                                       ),
                                                        ),
                                       "antivirus_other"=>array(
                                                        "headline"=>__("Other Antivirus"),
                                                        "sql"=>"SELECT * from software WHERE software_uuid = '" . $_GET["pc"] . "' AND software_timestamp = '".$GLOBAL["system_timestamp"]."'
                                                                                             AND (software_name LIKE '%Avast%'
                                                                                                  OR software_name LIKE '%Antivir%'
                                                                                                  OR software_name LIKE '%Internet Security%'
                                                                                                  OR software_name LIKE '%Virus%')",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/firewall_l.png",
                                                        "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                       ),
                                                        ),
                                       "nmap"=>array(
                                                        "headline"=>__("Open Ports discovered by Nmap"),
                                                        "sql"=>"SELECT * from nmap_ports WHERE nmap_other_id = '" . $_REQUEST["pc"] . "' ORDER BY nmap_port_number",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/nmap_l.png",
                                                        "fields"=>array("10"=>array("name"=>"nmap_port_number", "head"=>__("Port"),),
                                                                        "20"=>array("name"=>"nmap_port_proto", "head"=>__("Protocol"),),
                                                                        "30"=>array("name"=>"nmap_port_name", "head"=>__("Service"),),
                                                                        "40"=>array("name"=>"nmap_port_version", "head"=>__("Version"),),
                                                                       ),
                                                        ),

                                     ),
                      );
?>
