<?php

$query_array=array("views"=>array(__("iis")=>array(
                                                   "headline"=>__("IIS Settings"),
                                                   "sql"=>"SELECT * FROM iis WHERE iis_uuid = '".$_GET["pc"]."' AND iis_timestamp = '".$GLOBALS["timestamp"]."' ",
                                                   "image"=>"images/browser_l.png",
                                                   "fields"=>array("10"=>array("name"=>"iis_description", "head"=>__("Description"),),
                                                                   "20"=>array("name"=>"iis_home_directory", "head"=>__("Home Directory"),),
                                                                   "30"=>array("name"=>"iis_directory_browsing", "head"=>__("Directory Browsing"),),
                                                                   "40"=>array("name"=>"iis_default_documents", "head"=>__("Default Documents"),),
                                                                   "50"=>array("name"=>"iis_logging_enabled", "head"=>__("Logging Enabled"),),
                                                                   "60"=>array("name"=>"iis_logging_format", "head"=>__("Logging Format"),),
                                                                   "70"=>array("name"=>"iis_logging_time_period", "head"=>__("Logging Period"),),
                                                                   "80"=>array("name"=>"iis_logging_dir", "head"=>__("Logging Directory"),),
                                                                   "90"=>array("name"=>"iis_secure_ip", "head"=>__("Secure IP / Port"),),
                                                                   "100"=>array("name"=>"iis_secure_port", "head"=>__("IP Address / Port / Host Header"),),
                                                                   "110"=>array("name"=>"IP_Settings",
                                                                                "head"=>__("IP Settings"),
                                                                                "get"=>array("name"=>__("Click me!"),
                                                                                             "file"=>"list.php",
                                                                                             "title"=>__("Click me!"),
                                                                                             "var"=>array("pc"=>"%iis_uuid",
                                                                                                          "view"=>"iis_ips_for_system",
                                                                                                         ),
                                                                                            ),
                                                                                ),
                                                                   "120"=>array("name"=>"Virtual_Hosts",
                                                                                "head"=>__("Virtual Hosts"),
                                                                                "get"=>array("name"=>__("Click me!"),
                                                                                             "file"=>"list.php",
                                                                                             "title"=>__("Click me!"),
                                                                                             "var"=>array("pc"=>"%iis_uuid",
                                                                                                          "view"=>"iis_vhosts_for_system",
                                                                                                         ),
                                                                                            ),
                                                                                ),

                                                                  ),
                                                ),
                                 ),
                  );
?>
