<?php

$query_array=array("name"=>__("OS Information"),
                   "image"=>"images/os_l.png",
                   "views"=>array("summary"=>array(
                                                    "headline"=>__("Summary"),
                                                    "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $_GET["pc"] . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "image"=>"./images/summary_l.png",
                                                    "fields"=>array("10"=>array("name"=>"system_name",),
                                                                    "20"=>array("name"=>"system_description",),
                                                                    "30"=>array("name"=>"system_registered_user",),
                                                                    "40"=>array("name"=>"system_os_name",),
                                                                    "50"=>array("name"=>"system_vendor",),
                                                                    "60"=>array("name"=>"system_model",),
                                                                    "70"=>array("name"=>"system_id_number",),
                                                                   ),
                                                    ),
                                   "os"=>array(
                                                    "headline"=>__("OS Information"),
                                                    "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $_GET["pc"] . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "image"=>"images/os_l.png",
                                                    "fields"=>array("10"=>array("name"=>"system_os_name",),
                                                                    "20"=>array("name"=>"system_registered_user",),
                                                                    "30"=>array("name"=>"system_organisation",),
                                                                    "40"=>array("name"=>"system_build_number",),
                                                                    "50"=>array("name"=>"system_service_pack",),
                                                                    "60"=>array("name"=>"system_windows_directory",),
                                                                    "70"=>array("name"=>"system_serial_number",),
                                                                    "80"=>array("name"=>"date_system_install",),
                                                                    "90"=>array("name"=>"system_language",),
                                                                    "100"=>array("name"=>"time_caption",),
                                                                    "110"=>array("name"=>"time_daylight",),
                                                                   ),
                                                    ),
                                   "software"=>array(
                                                    "headline"=>__("Software"),
                                                    "sql"=>"SELECT software_name, software_version, software_publisher, software_url
                                                            FROM software, system
                                                            WHERE system_uuid = '".$_REQUEST["pc"]."' AND software_uuid = system_uuid AND software_timestamp = system_timestamp
                                                            AND (software_name LIKE 'Internet%' OR software_name LIKE 'DirectX%' OR software_name = 'Windows Media Player')
                                                              ",
                                                    "image"=>"images/software_l.png",
                                                    "fields"=>array("10"=>array("name"=>"software_name",),
                                                                    "20"=>array("name"=>"software_version",),
                                                                   ),
                                                    ),
                                   "network_card"=>array(
                                                    "headline"=>__("Network Card"),
                                                    "sql"=>"SELECT * FROM network_card WHERE net_uuid = '" . $_GET["pc"] . "' AND net_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "image"=>"images/network_device_l.png",
                                                    "fields"=>array("10"=>array("name"=>"net_adapter_type",),
                                                                    "20"=>array("name"=>"net_description",),
                                                                    "30"=>array("name"=>"net_manufacturer",),
                                                                    "40"=>array("name"=>"net_mac_address",),
                                                                    "50"=>array("name"=>"net_ip_address",),
                                                                    "60"=>array("name"=>"net_ip_subnet",),
                                                                    "70"=>array("name"=>"net_dns_server",),
                                                                    "80"=>array("name"=>"net_dns_server_2",),
                                                                    "90"=>array("name"=>"net_wins_primary",),
                                                                    "10"=>array("name"=>"net_wins_secondary",),
                                                                    "110"=>array("name"=>"net_dhcp_enabled",),
                                                                    "120"=>array("name"=>"net_dhcp_server",),
                                                                   ),
                                                    ),
                                   "shares"=>array(
                                                    "headline"=>__("Shared Drives"),
                                                    "sql"=>"SELECT * FROM shares WHERE shares_uuid = '".$_REQUEST["pc"]."' AND shares_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY shares_path, shares_name",
                                                    "image"=>"images/shared_drive_l.png",
                                                    "fields"=>array("10"=>array("name"=>"shares_name",),
                                                                    "20"=>array("name"=>"shares_caption",),
                                                                    "30"=>array("name"=>"shares_path",),
                                                                   ),
                                                    ),
                                ),
                  );
?>
