<?php

$query_array=array("views"=>array(__("iis")=>array(
                                                   "headline"=>__("IIS Settings"),
                                                   "sql"=>"SELECT * FROM iis WHERE iis_uuid = '".$_GET["pc"]."' AND iis_timestamp = '".$GLOBALS["timestamp"]."' ",
                                                   "image"=>"images/browser_l.png",
                                                   "fields"=>array("10"=>array("name"=>"iis_description",),
                                                                   "20"=>array("name"=>"iis_home_directory",),
                                                                   "30"=>array("name"=>"iis_directory_browsing",),
                                                                   "40"=>array("name"=>"iis_default_documents",),
                                                                   "50"=>array("name"=>"iis_logging_enabled",),
                                                                   "60"=>array("name"=>"iis_logging_format",),
                                                                   "70"=>array("name"=>"iis_logging_time_period",),
                                                                   "80"=>array("name"=>"iis_logging_dir",),
                                                                   "90"=>array("name"=>"iis_secure_ip",),
                                                                   "100"=>array("name"=>"iis_secure_port",),
                                                                   "100"=>array("name"=>"IP Settings",
                                                                                "get"=>array("name"=>__("Click me!"),
                                                                                             "file"=>"list.php",
                                                                                             "title"=>__("Click me!"),
                                                                                             "var"=>array("pc"=>"%iis_uuid",
                                                                                                          "view"=>"iis_ips_for_system",
                                                                                                         ),
                                                                                            ),
                                                                                ),
                                                                   "110"=>array("name"=>"Virtual Hosts",
                                                                                "get"=>array("name"=>__("Click me!"),
                                                                                             "file"=>"list.php",
                                                                                             "title"=>__("Click me!"),
                                                                                             "var"=>array("pc"=>"%iis_uuid",
                                                                                                          "view"=>"iis_vhosts_for_system",
                                                                                                         ),
                                                                                            ),
                                                                                ),

                                                                  ),
                                                ),
                                 ),
                  );
?>
